### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by briandonovan** [wendlers/atom-sermon#1]
**Atom**: 1.22.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [sermon](https://github.com/wendlers/atom-sermon) package 0.1.6

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///C:/Users/user/AppData/Local/atom/app-1.22.0-beta0/resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at exit (/packages/sermon/lib/sermon.js:112:43)
    at triggerExitCallback (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -0:32.7.0 sermon:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
arduino-toolbelt 0.1.1 
arduino-upload 1.3.2 
atom-beautify 0.30.5 
atom-material-ui 2.0.4 
atom-minify 0.8.0 
atomic-emacs 0.12.1 
aurora-theme 1.2.2 
autocomplete-python 1.10.3 
build-arduino 0.1.1 
busy-signal 1.4.3 
cssbeautify 1.3.0 
disable-keybindings 0.6.0 
editing-diff 0.2.1 
editor-settings 1.1.3 
editor-stats 0.17.0 
force-tab 0.2.4 
git-time-machine 1.5.9 
Hydrogen undefined 
ink 0.7.7 
intentions 1.1.5 
julia-client 0.6.4 
language-arduino 0.4.3 
language-ino 0.2.0 
language-julia 0.12.0 
language-latex 1.1.1 
latex 0.48.0 
latex-completions 0.3.3 
latex-plus 0.9.1 
latexer 0.3.0 
latextools 0.8.5 
linter 2.2.0 
linter-autocomplete-jing undefined 
linter-chktex 1.3.1 
linter-ui-default 1.6.10 
MagicPython 1.0.12 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
note-book 0.1.0 
package-cop 0.2.10 
power-editor 0.2.0 
preview-inline 1.4.7 
python-indent 1.1.2 
qolor 0.4.2 
script 3.16.0 
sermon 0.1.6 
tabs-to-spaces 1.0.3 
termination 0.6.1 
tool-bar 1.1.0 
trailing-spaces 0.4.0 
uber-juno 0.1.2 
whitespacer 1.1.1 
ymacs-editor 1.0.10 
```

**Comment by EduTechTools** [comment]
Wiser developers than I will have a better solution, but my version of this issue (MacOS 10.15.2) was that I had installed the dependency, PySerial, via the homebrew edition of Python 3 (and pip3) and the required path to Python was /usr/local/bin/python3 instead of /usr/local/bin/python.  

Modifying pysermon.py line 1 to #!/usr/local/bin/python3 resolved the issue for me.
